[package]
name = "orjson"
version = "2.0.4"
authors = ["ijl <ijl@mailbox.org>"]
description = "Fast, correct Python JSON library"
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/ijl/orjson"
homepage = "https://github.com/ijl/orjson"
readme = "README.md"
keywords = ["fast", "json", "datetime", "rfc", "3339"]
include = ["Cargo.toml", "src/*", "data/*", "test/*.py", "README.md", "CHANGELOG.md", "LICENSE-APACHE", "LICENSE-MIT"]

[lib]
name = "orjson"
crate-type = ["cdylib"]

[package.metadata.pyo3-pack]
classifier = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "License :: OSI Approved :: MIT License",
    "License :: OSI Approved",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python",
    "Programming Language :: Rust",
]

[dependencies]
encoding_rs = { version = "0.8", default_features = false, features = ["simd-accel"] }
itoa = { version = "0.4", default_features = false }
pyo3 = { git = "https://github.com/PyO3/pyo3.git", rev = "dc2fc80f4aeb89dd645a20620b292bfea4756228", features = ["extension-module"]}
serde = { version = "1", default_features = false }
serde_json = { version = "1", default_features = false }
smallvec = { version = "0.6", default_features = false, features = ["union"] }

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = 3
panic = "abort"
