[project]
name = "orjson"
repository = "https://github.com/ijl/orjson"

[build-system]
build-backend = "maturin"
requires = ["maturin>=0.12.18,<0.13"]

[tool.maturin]
sdist-include = ["build.rs", "Cargo.lock", "include"]
strip = true

[tool.black]
line-length = 88
target-version = ["py37"]
include = ".pyi?$"
