[project]
name = "orjson"
repository = "https://github.com/ijl/orjson"

[build-system]
build-backend = "maturin"
requires = ["maturin>=0.12.3,<0.13"]

[tool.maturin]
sdist-include = ["Cargo.lock"]
strip = true

[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39']
include = '\.pyi?$'
