[project]
name = "orjson"
repository = "https://github.com/ijl/orjson"

[build-system]
build-backend = "maturin"
requires = ["maturin>=0.7.7,<0.8"]

[tool.maturin]
manylinux = "off"
rustc-extra-args = "-Zmutable-noalias -C target-feature=+sse2"
strip = "on"

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
