variables:
  toolchain: nightly-2020-02-18

jobs:

- job: linux_sdist
  pool:
    vmImage: ubuntu-18.04
  variables:
    interpreter: python3.7
    target: x86_64-unknown-linux-gnu
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
  - checkout: self
  - template: ./azure-sdist.yml

- job: linux_python39
  pool:
    vmImage: ubuntu-18.04
  container: python:3.9-rc-buster
  variables:
    interpreter: python3.9
    manylinux: 1
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
    target: x86_64-unknown-linux-gnu
  steps:
  - checkout: self
  - template: ./azure-linux-container.yml

- job: linux_python38
  pool:
    vmImage: ubuntu-18.04
  container: python:3.8-buster
  variables:
    interpreter: python3.8
    manylinux: 1
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
    target: x86_64-unknown-linux-gnu
  steps:
  - checkout: self
  - template: ./azure-linux-container.yml

- job: linux_python37
  pool:
    vmImage: ubuntu-18.04
  container: python:3.7-buster
  variables:
    interpreter: python3.7
    manylinux: 1
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
    target: x86_64-unknown-linux-gnu
  steps:
  - checkout: self
  - template: ./azure-linux-container.yml

- job: linux_python36
  pool:
    vmImage: ubuntu-18.04
  container: python:3.6-buster
  variables:
    interpreter: python3.6
    manylinux: 1
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
    target: x86_64-unknown-linux-gnu
  steps:
  - checkout: self
  - template: ./azure-linux-container.yml

- job: macos_python38
  pool:
    vmImage: macOS-10.14
  variables:
    interpreter: python3.8
    manylinux: off
    target: x86_64-apple-darwin
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
  - checkout: self
  - template: ./azure-posix.yml

- job: macos_python37
  pool:
    vmImage: macOS-10.14
  variables:
    interpreter: python3.7
    manylinux: off
    target: x86_64-apple-darwin
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
  - checkout: self
  - template: ./azure-posix.yml

- job: macos_python36
  pool:
    vmImage: macOS-10.14
  variables:
    interpreter: python3.6
    manylinux: off
    target: x86_64-apple-darwin
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - checkout: self
  - template: ./azure-posix.yml

- job: win_python38
  pool:
    vmImage: windows-2019
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.8.1\x64\python.exe
    target: x86_64-pc-windows-msvc
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml

- job: win_python37
  pool:
    vmImage: windows-2019
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.7.6\x64\python.exe
    target: x86_64-pc-windows-msvc
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml

- job: win_python36
  pool:
    vmImage: windows-2019
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.6.8\x64\python.exe
    target: x86_64-pc-windows-msvc
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml
