pr:
  branches:
    include:
    - '*'

variables:
  toolchain: nightly-2022-02-13

jobs:

- job: linux_sdist
  pool:
    vmImage: ubuntu-20.04
  container: quay.io/pypa/manylinux_2_24_x86_64:latest
  variables:
    interpreter: python3.9
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/opt/python/cp39-cp39/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
    target: x86_64-unknown-linux-gnu
  steps:
  - checkout: self
  - template: ./azure-sdist.yml

- job: linux_stable
  pool:
    vmImage: ubuntu-20.04
  container: quay.io/pypa/manylinux_2_24_x86_64:latest
  variables:
    interpreter: python3.9
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/opt/python/cp39-cp39/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
    target: x86_64-unknown-linux-gnu
    toolchain: 1.54.0
  steps:
  - checkout: self
  - template: ./azure-sdist.yml

- job: linux_debug
  pool:
    vmImage: ubuntu-20.04
  container: quay.io/pypa/manylinux_2_24_x86_64:latest
  variables:
    extra: '--cargo-extra-args="--features=unstable-simd"'
    interpreter: python3.9
    compatibility: off
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/opt/python/cp39-cp39/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
  steps:
  - checkout: self
  - template: ./azure-debug.yml

- job: linux_python310_amd64_manylinux_2_24
  pool:
    vmImage: ubuntu-20.04
  container: quay.io/pypa/manylinux_2_24_x86_64:latest
  variables:
    extra: '--cargo-extra-args="--features=unstable-simd"'
    interpreter: python3.10
    compatibility: 2_24
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/opt/python/cp310-cp310/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
  steps:
  - checkout: self
  - template: ./azure-manylinux.yml

- job: linux_python39_amd64_manylinux_2_24
  pool:
    vmImage: ubuntu-20.04
  container: quay.io/pypa/manylinux_2_24_x86_64:latest
  variables:
    extra: '--cargo-extra-args="--features=unstable-simd"'
    interpreter: python3.9
    compatibility: 2_24
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/opt/python/cp39-cp39/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
  steps:
  - checkout: self
  - template: ./azure-manylinux.yml

- job: linux_python38_amd64_manylinux_2_24
  pool:
    vmImage: ubuntu-20.04
  container: quay.io/pypa/manylinux_2_24_x86_64:latest
  variables:
    extra: '--cargo-extra-args="--features=unstable-simd"'
    interpreter: python3.8
    compatibility: 2_24
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/opt/python/cp38-cp38/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
  steps:
  - checkout: self
  - template: ./azure-manylinux.yml

- job: linux_python37_amd64_manylinux_2_24
  pool:
    vmImage: ubuntu-20.04
  container: quay.io/pypa/manylinux_2_24_x86_64:latest
  variables:
    extra: '--cargo-extra-args="--features=unstable-simd"'
    interpreter: python3.7
    compatibility: 2_24
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/opt/python/cp37-cp37m/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
  steps:
  - checkout: self
  - template: ./azure-manylinux.yml

- job: linux_python39_amd64_manylinux2014
  pool:
    vmImage: ubuntu-20.04
  container: quay.io/pypa/manylinux2014_x86_64:2021-07-03-d4d5413
  variables:
    extra: '--cargo-extra-args="--features=unstable-simd"'
    interpreter: python3.9
    compatibility: 2014
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/opt/python/cp39-cp39/bin:/opt/rh/devtoolset-9/root/usr/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  steps:
  - checkout: self
  - template: ./azure-manylinux.yml

- job: linux_python38_amd64_manylinux2014
  pool:
    vmImage: ubuntu-20.04
  container: quay.io/pypa/manylinux2014_x86_64:2021-07-03-d4d5413
  variables:
    extra: '--cargo-extra-args="--features=unstable-simd"'
    interpreter: python3.8
    compatibility: 2014
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/opt/python/cp38-cp38/bin:/opt/rh/devtoolset-9/root/usr/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  steps:
  - checkout: self
  - template: ./azure-manylinux.yml

- job: linux_python37_amd64_manylinux2014
  pool:
    vmImage: ubuntu-20.04
  container: quay.io/pypa/manylinux2014_x86_64:2021-07-03-d4d5413
  variables:
    extra: '--cargo-extra-args="--features=unstable-simd"'
    interpreter: python3.7
    compatibility: 2014
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/opt/python/cp37-cp37m/bin:/opt/rh/devtoolset-9/root/usr/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  steps:
  - checkout: self
  - template: ./azure-manylinux.yml

- job: macos_python310_amd64
  pool:
    vmImage: macOS-10.15
  variables:
    interpreter: python3.10
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true
  - checkout: self
  - template: ./azure-macos.yml

- job: macos_python39_amd64
  pool:
    vmImage: macOS-10.15
  variables:
    interpreter: python3.9
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      addToPath: true
  - checkout: self
  - template: ./azure-macos.yml

- job: macos_python38_amd64
  pool:
    vmImage: macOS-10.15
  variables:
    interpreter: python3.8
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
  - checkout: self
  - template: ./azure-macos.yml

- job: macos_python37_amd64
  pool:
    vmImage: macOS-10.15
  variables:
    interpreter: python3.7
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
  - checkout: self
  - template: ./azure-macos.yml

- job: win_python310_amd64
  pool:
    vmImage: windows-2019
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.10.1\x64\python.exe
    target: x86_64-pc-windows-msvc
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml

- job: win_python39_amd64
  pool:
    vmImage: windows-2019
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.9.9\x64\python.exe
    target: x86_64-pc-windows-msvc
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml

- job: win_python38_amd64
  pool:
    vmImage: windows-2019
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.8.10\x64\python.exe
    target: x86_64-pc-windows-msvc
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml

- job: win_python37_amd64
  pool:
    vmImage: windows-2019
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
    target: x86_64-pc-windows-msvc
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml
