name: manylinux_2_28
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
jobs:
  manylinux_2_28:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: [
          { version: '3.7', abi: 'cp37-cp37m' },
          { version: '3.8', abi: 'cp38-cp38' },
          { version: '3.9', abi: 'cp39-cp39' },
          { version: '3.10', abi: 'cp310-cp310' },
          { version: '3.11', abi: 'cp311-cp311' },
        ]
    env:
      PATH: /github/home/.local/bin:/github/home/.cargo/bin:/opt/python/${{ matrix.python.abi }}/bin:/opt/rh/gcc-toolset-12/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      CC: "clang"
      CFLAGS: "-O2 -fno-plt -flto=thin"
      LDFLAGS: "-O2 -flto=thin -fuse-ld=lld -Wl,--as-needed"
      RUSTFLAGS: "-C linker=clang -C link-arg=-fuse-ld=lld"
      CARGO_UNSTABLE_SPARSE_REGISTRY: "true"
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64:latest
      options: --user 0
    steps:
    - run: yum install -y clang lld
    - run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly-2022-11-20 --profile minimal -y
    - run: rustup component add rust-src --toolchain nightly-2022-11-20-x86_64-unknown-linux-gnu
    - uses: actions/checkout@v2
    - run: python3 -m pip install --user --upgrade pip "maturin>=0.14,<0.15" wheel
    - run: |
        maturin build --release --strip \
          --features=unstable-simd,yyjson \
          --compatibility manylinux_2_28 \
          --interpreter python${{ matrix.python.version }} \
          -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort \
          --target=x86_64-unknown-linux-gnu
    - run: python3 -m pip install --user target/wheels/orjson*.whl
    - run: python3 -m pip install --user -r test/requirements.txt -r integration/requirements.txt
    - run: pytest -s -rxX -v test
    - run: ./integration/run thread
    - run: ./integration/run http
    - run: git config --global --add safe.directory /__w/orjson/orjson
    - name: deploy
      run: maturin upload --skip-existing --username "$MATURIN_USERNAME" target/wheels/orjson-*.whl
      if: "startsWith(github.ref, 'refs/tags/')"
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
